- name: "Wait for VMware tools to become available on {{ vm_name }}"
  vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
#    folder: "/{{datacenter}}/vm"